# Generated by Django 6.0.6 on 2026-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('UPS', 'UPS'), ('Generator', 'Generator'), ('Battery', 'Battery'), ('Solar Panel', 'Solar Panel'), ('Control Panel', 'Control Panel'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
